nb_epochs: 10
gpus: 1
backbone: 'resnet50'
train_bn: True
train: '../data/training'
validation: '../data/validation'
batch_size: 8
lr: 0.0001 
lr_scheduler_gamma: 0.01 
num_workers: -1
n_classes: 10
FC1: 2048
FC2: 256
FC3: 32
milestones: [3, 5, 7]
