input_size : [450, 450, 3]
nb_epochs: 130
gpus: 1
backbone: 'resnet50'
train_bn: True
train: '../../data/C-NMC_Leukemia/training_data/fold_0'
validation: '../../data/C-NMC_Leukemia/training_data/fold_1'
batch_size: 8 
lr: 0.0001 
lr_scheduler_gamma: 0.01 
num_workers: -1
n_classes: 2 
FC1: 2048
FC2: 256
FC3: 32
milestones: [3, 5, 7]
trained_path: 'lightning_logs/version_4/checkpoints/leukemia_resnet50_epoch=94.ckpt'
torch_model_path: 'models/leukemia_resnet50_classifier.pt'